# Stage 1: Build the Angular application
FROM node:18 AS build
WORKDIR /app
COPY angular/package*.json ./
RUN npm install
# Install Angular CLI globally
RUN npm install -g @angular/cli
COPY angular ./
RUN ng build

# Stage 2: Serve the Angular application with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/lab-sequence/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

