# Stage 1: Build the Quarkus application
FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY quarkus/pom.xml .
COPY quarkus/src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run the Quarkus application
FROM openjdk:21
WORKDIR /work
COPY --from=build /workspace/target/ /work/build
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/work/build/quarkus-app/quarkus-run.jar"]
